# Generated by Django 4.1.3 on 2023-02-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Houseuploads',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('house_name', models.CharField(max_length=100)),
                ('main_img', models.ImageField(upload_to='post_images')),
                ('houseimg_one', models.ImageField(upload_to='post_images')),
                ('houseimg_two', models.ImageField(upload_to='post_images')),
                ('houseimg_three', models.ImageField(upload_to='post_images')),
                ('houseimg_four', models.ImageField(upload_to='post_images')),
                ('houseimg_five', models.ImageField(upload_to='post_images')),
                ('details', models.TextField()),
                ('housetype', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('rentmonth', models.CharField(max_length=10)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default='blank-img.png', upload_to='main_images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
