# Generated by Django 4.1.3 on 2023-02-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_houseuploads_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='agentname',
        ),
    ]
